cn:
  location: "地点："
  you-can-also: "您也可以："
  donate: "捐赠"
  time: "东湾每周六下午；南湾每周五晚，"
  performance: "演出："
  buy-tickets: "购票"
  except-holidays: "，公共假期前除外"
en:
  except-holidays: ", except public holidays"
  buy-tickets: "Buy Tickets"
  donate: "Donate"
  time: "East Bay on every Saturday afternoon. South Bay on every Friday night"
  location: "Location: "
  performance: "Open-mic: "
  you-can-also: "You can also: "
